-- Migration number: 0001 	 2023-05-01T09:47:37.963Z
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE paths (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  route TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);