-- Migration number: 0002 	 2023-05-01T13:18:49.477Z
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE visitors (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  path_id INTEGER NOT NULL,
  ip_address TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);